//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreId { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public Nullable<int> QnId { get; set; }
        public Nullable<int> Answer { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Question Question { get; set; }
    }
}
